# serverless.yml
component: http # (必选) 组件名称
name: Odin # 必选) 组件实例名称.

inputs:
  region: ap-guangzhou # 云函数所在区域
  src: # 在指定存储桶bucket中已经存在了object代码，直接部署
    # src: ./ # 本地需要打包的文件目录
    bucket: odin-pkg-1251999712 # bucket name，当前会默认在bucket name后增加 appid 后缀, 本例中为 bucket01-appid
    object: odin.zip  # bucket key 指定存储桶内的文件
  faas: # 函数配置相关
    framework: nestjs
    runtime: Nodejs18.15
    name: odin # 云函数名称
    timeout: 10 # 超时时间，单位秒
    memorySize: 1024 # 内存大小，默认 512 MB
    vpc:
      vpcId: vpc-r247gi5n # 私有网络的Id
      subnetId: subnet-id8bf62i # 子网ID
  apigw:
    isDisabled: true
  layers: #layer配置
    - name: odinLayer #  layer名称
      version: 1 #  版本
