const { toolbarItems } = window["Doc"];

export default {
  agentConfig: {
    default: {
      items: [
        // toolbarItems.cardSelect,
        // "|",
        toolbarItems.undo,
        toolbarItems.redo,
        toolbarItems.formatPainter,
        toolbarItems.clearFormat,
        "|",
        toolbarItems.style,
        toolbarItems.fontsize,
        toolbarItems.bold,
        toolbarItems.italic,
        toolbarItems.strikethrough,
        toolbarItems.underline,
        // toolbarItems.mixedTextStyle,
        "|",
        toolbarItems.color,
        toolbarItems.bgColor,
        "|",
        toolbarItems.alignment,
        toolbarItems.unorderedList,
        toolbarItems.orderedList,
        toolbarItems.indent,
        toolbarItems.lineHeight,
        "|",
        // toolbarItems.taskList,
        // toolbarItems.link,
        // toolbarItems.quote,
        toolbarItems.hr,
      ],
    },
    // table选区工具栏
    table: {
      items: [
        // toolbarItems.cardSelect,
        // "|",
        toolbarItems.undo,
        toolbarItems.redo,
        toolbarItems.formatPainter,
        toolbarItems.clearFormat,
        "|",
        toolbarItems.style,
        toolbarItems.fontsize,
        toolbarItems.bold,
        toolbarItems.italic,
        toolbarItems.strikethrough,
        toolbarItems.underline,
        toolbarItems.mixedTextStyle,
        "|",
        toolbarItems.color,
        toolbarItems.bgColor,
        toolbarItems.tableCellBgColor,
        toolbarItems.tableBorderVisible,
        "|",
        toolbarItems.alignment,
        toolbarItems.tableVerticalAlign,
        toolbarItems.tableMergeCell,
        "|",
        toolbarItems.unorderedList,
        toolbarItems.orderedList,
        toolbarItems.indent,
        toolbarItems.lineHeight,
        "|",
        toolbarItems.taskList,
        toolbarItems.link,
        toolbarItems.quote,
        toolbarItems.hr,
      ],
    },
  },
};
